### ISSUE TITLE
Tagging Docker Images

### ISSUE THREAD

**Issue by baccenfutter** [FluxFail/flux.fail#16]
@bergie: How much effort would it take to automatically tag the Docker images corresponding to the Git tags we push to Github. As of now, the only tag the images support is `latest`, which makes roll-backs kinda impossible.

**Comment by baccenfutter** [comment]
@bergie I tagged 0.1.2 and pushed. Travis ran through but I can not see any new tags on Docker hub.

**Comment by baccenfutter** [comment]
How about something like this?
```
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=sebestblog/travis-demo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
```
https://sebest.github.io/post/using-travis-ci-to-build-docker-images/

**Comment by bergie** [comment]
@baccenfutter I'd rather see it in deploy step, since that has better control on when it happens. But yeah, might be that we need to tweak the script in this PR

**Comment by bergie** [comment]
Travis docs: https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Comment by baccenfutter** [comment]
works.
