### ISSUE TITLE
Also affected

### ISSUE THREAD

**Issue by baccenfutter** [FluxFail/flux.fail#31]
# Userstory

As a user browsing the delay stream, I want to be able to acknowledge the delay report of another user by reporting myself as also affected by that delay. The benefit of acknowledging another user's delay is that the points a delay is worth varies depending on how many users have acknowledged it.

# AC

- ~[ ] add support for acknowledging other users' delays to the DelayForm component - an acknowledgement is a separate report with its parent field set to the ID of the other report. Consequentially, the points for a delay can be calculated by searching for all delays with their parent field set to this delay's ID.~
- ~[ ] add specification tests, accordingly.~

**Comment by baccenfutter** [comment]
After reiterating this, it turns out that there are several complications that initially seem to have not been considered.

The initial idea was to display a `+1` button on all delays reported by other users. Clicking that button would bring the user to a pre-populated `<DelayForm />` with the `parent` set to the `id` of the original report. Saving the form would create a new distinct DB entry.

1. We want to limit `+1` to only once per delay. It must be prohibited to `+1` a delay more than once.
2. We want to display all the `+1` entries in the `<DelayList />` as a single entry.
3. We want the user to still be able to edit and delete the own `+1` report.
4. We want the user of the original report be able to delete the report.

# Proposal
Instead of effectively writing a new entry to the DB for every `+1`, we could instead introduce a new column in the `delay` table of type JSONB. Whenever a user clicks `+1` an entry is added to the JSONB of the DB entry of the original report.

Example JSONB:
```json
[
  {
    "user": "${ID}",
    "scheduled_departure": "${ISODATE}",
    "location": "",
    "delay_minutes": 0,
    "comment": ""
  }
]
```

# Reasoning

1. It is quite cheap to prevent users from `+1`ing a delay more than once.
2. A delay is always only a single DB entry (but with more or less entries in the JSONB).
3. Calculating the points for a delay is rather cheap, basically `len(JSONB)` for every delay.
4. When the user of the original report deletes the report. the ownership could simply be transferred to the first user in the JSONB of the report or deleted if the JSONB is empty.

----
Cc: @bergie @cemcagras

**Comment by cemcagras** [comment]
@baccenfutter Did I understand you correct, that users should just be able to confirm already reported delays but shouldn't be able to edit any minutes/locations etc.? In this case we wouldn't need the last four fields from the suggested JSONB anymore and we could just administrate a list of userids/strings.

**Comment by baccenfutter** [comment]
@cemcagras: Not quite, users must be able to confirm already reported delays, but may specify their individual `scheduled_departure`, `location` and `delay_minutes`, because the could possibly be entering at a different station. Users must be able to edit/delete this data, thus we need the information in the JSONB.

**Comment by baccenfutter** [comment]
@cemcagras I will work out the details face2face with bergie. I'll have a look at your PR some time tomorrow.

**Comment by baccenfutter** [comment]
Solved.
