### ISSUE TITLE
Make Travis-CI builds pass

### ISSUE THREAD

**Issue by baccenfutter** [FluxFail/flux.fail#35]
@cemcagras: eine Sache, die du auch ganz nebenbei im Auge haben koenntest sind die zahlreichen Lint Fehler, die auch zum Failen des Builds fuehren - ab Zeile 701: 
- https://travis-ci.org/FluxFail/flux.fail/builds/467188067#L701

Ausserdem besteht scheinbar ein leicht zu schliessendes Security Problem:
- https://travis-ci.org/FluxFail/flux.fail/builds/467188067

**Comment by baccenfutter** [comment]
Die Zeilen mit `error` muessen weg, die Zeilen mit `warning` sind zweitrangig.

**Comment by cemcagras** [comment]
@baccenfutter ja, ich kümmere mich gerade darum.

**Comment by baccenfutter** [comment]
Deluxe!
