### ISSUE TITLE
Not able to edit my own delays in the past with error screen

### ISSUE THREAD

**Issue by Tourountzis** [FluxFail/flux.fail#42]
I have the issue under Firefox 64.0 (64 bit Windows 10 10803) that i can not save in the past created delays.
After i want to schwitch through the Home button to she start view i become following error screen.
<img width="453" alt="fluxfailwin" src="https://user-images.githubusercontent.com/1280228/50375415-38d72780-05fd-11e9-9802-fea7820b154d.png">

**Comment by baccenfutter** [comment]
Thank's a lot for reporting this! I've deployed a fix that disables the save button for as long as not all mandatory fields are supplied.
