### ISSUE TITLE
Support older iOS within authentication mechanism

### ISSUE THREAD

**Issue by baccenfutter** [FluxFail/flux.fail#5]
Currently, the authentication mechanism (whatever is sending out the auth-mail) is presenting an eternal spinner when clicking the "Send Magic-Link" button on iPhone 4. I am aware that that is a pretty old iOS version. Is it worth the effort to support such old iOS versions?

**Comment by bergie** [comment]
This is likely the lack of [fetch API](https://caniuse.com/#feat=fetch).

iPhone 4 stopped getting updates at iOS 7.1.2, so there can be lots of other modern web stuff missing
https://apple.stackexchange.com/questions/174061/what-is-the-latest-ios-version-for-iphone-4

**Comment by baccenfutter** [comment]
Moved to #10.
